services:
  authorization-server:
    image: 'roboskeletron/authserver'
    depends_on: [postgres]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_server_dev_db
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      logging.level.com.roboskeletron: info
    ports:
      - 9000:9000
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: auth_server_dev_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devP@ssw0rd
    ports:
      - 5433:5432